services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8080:8080

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
