SHARE_COMPANIES = {
    "PETR4": "Petroleo Brasileiro SA Petrobras Preference Shares",
    "VALE3": "Vale S.A.",
    "BBAS3": "Banco do Brasil SA",
    "ITUB4": "Itaú Unibanco",
    "BBDC4": "Banco Bradesco SA Preference Shares",
    "JBSS3": "JBS",
    "ABEV3": "Ambev",
    "MGLU3": "Magazine Luiza",
    "B3SA3": "B3 SA - Brasil Bolsa Balcao",
    "RENT3": "Localiza",
    "ITSA4": "Itausa SA Preference Shares",
    "PETR3": "Petroleo Brasileiro SA Petrobras",
    "ELET3": "Centrais Eletricas Brasileiras SA",
    "BRFS3": "BRF",
    "KROT3": "Kroton",
    "UGPA3": "Grupo Ultra",
    "VVAR3": "Via Varejo",
    "GOLL4": "Gol Linhas Aereas Inteligentes SA Preference Shares",
    "GGBR4": "Gerdau PN",
    "PCAR4": "Grupo Pão de Açúcar",
    "RAIL3": "Rumo SA",
    "AZUL4": "Azul SA",
    "GNDI3": "NOTRE DAME INTERMEDICA ON",
    "ELET6": "Centrais Eletricas Brasileiras SA Preference Shares Series B",
    "MRFG3": "Marfrig",
    "CSNA3": "Companhia Siderúrgica Nacional",
    "LREN3": "Lojas Renner",
    "IRBR3": "IRB (Re)",
    "BRDT3": "Petrobras Distribuidora",
    "CCRO3": "Grupo CCR",
    "SUZB3": "Suzano Papel e Celulose",
    "RADL3": "Raia Drogasil",
    "GOAU4": "Metalurgica Gerdau SA Preference Shares",
    "BBSE3": "BB Seguridade",
    "CIEL3": "Cielo",
    "CVCB3": "CVC",
    "NATU3": "Natura",
    "BTOW3": "B2W Digital",
    "CMIG4": "Cemig PN",
    "SBSP3": "Sabesp"
}

SHARE_COMPANIES_LOGO = {
    "PETR4": "PETR4.gif",
    "VALE3": "VALE3.jpg",
    "BBAS3": "BBAS3.png",
    "ITUB4": "ITUB4.png",
    "BBDC4": "BBDC4.png",
    "JBSS3": "JBSS3.png",
    "ABEV3": "ABEV3.png",
    "MGLU3": "MGLU3.png",
    "B3SA3": "B3SA3.png",
    "RENT3": "RENT3.svg",
    "ITSA4": "ITSA4.png",
    "PETR3": "PETR4.gif",
    "ELET3": "ELET3.jpg",
    "BRFS3": "BRFS3.jpeg",
    "KROT3": "KROT3.jpg",
    "UGPA3": "UGPA3.png",
    "VVAR3": "VVAR3.webp",
    "GOLL4": "GOLL4.png",
    "GGBR4": "GGBR4.png",
    "PCAR4": "PCAR4.png",
    "RAIL3": "RAIL3.png",
    "AZUL4": "AZUL4.svg",
    "GNDI3": "GNDI3.png",
    "ELET6": "ELET6.png",
    "MRFG3": "MRFG3.png",
    "CSNA3": "CSNA3.png",
    "LREN3": "LREN3.png",
    "IRBR3": "IRBR3.png",
    "BRDT3": "PETR4.gif",
    "CCRO3": "CCRO3.jpg",
    "SUZB3": "SUZB3.png",
    "RADL3": "RADL3.png",
    "GOAU4": "GOAU4.png",
    "BBSE3": "BBSE3.png",
    "CIEL3": "CIEL3.png",
    "CVCB3": "CVCB3.png",
    "NATU3": "NATU3.jpg",
    "BTOW3": "BTOW3.webp",
    "CMIG4": "CMIG4.webp",
    "SBSP3": "SBSP3.svg"
    
}
